name: Execute Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM Install
        run: npm ci

      - name: Run tests 🧪
        run: npm run test

  report:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      statuses: write
    steps:
      - name: Report success
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          status: "success"
          context: "vitest-unit-tests" 